services:
  rag-analytics:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./data:/app/data
      - ./db:/app/db
      - ./chroma_db:/app/chroma_db
    restart: unless-stopped